#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQLNS.LQTOSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhanMemQLNS")]
	public partial class DataClasses_NSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBangCong(BangCong instance);
    partial void UpdateBangCong(BangCong instance);
    partial void DeleteBangCong(BangCong instance);
    partial void InsertPhongBan(PhongBan instance);
    partial void UpdatePhongBan(PhongBan instance);
    partial void DeletePhongBan(PhongBan instance);
    partial void InsertBangLuong(BangLuong instance);
    partial void UpdateBangLuong(BangLuong instance);
    partial void DeleteBangLuong(BangLuong instance);
    partial void InsertChiTietHĐ(ChiTietHĐ instance);
    partial void UpdateChiTietHĐ(ChiTietHĐ instance);
    partial void DeleteChiTietHĐ(ChiTietHĐ instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertDangNhap(DangNhap instance);
    partial void UpdateDangNhap(DangNhap instance);
    partial void DeleteDangNhap(DangNhap instance);
    partial void InsertHopDong(HopDong instance);
    partial void UpdateHopDong(HopDong instance);
    partial void DeleteHopDong(HopDong instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    #endregion
		
		public DataClasses_NSDataContext() : 
				base(global::PhanMemQLNS.Properties.Settings.Default.PhanMemQLNSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_NSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_NSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_NSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_NSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangCong> BangCongs
		{
			get
			{
				return this.GetTable<BangCong>();
			}
		}
		
		public System.Data.Linq.Table<PhongBan> PhongBans
		{
			get
			{
				return this.GetTable<PhongBan>();
			}
		}
		
		public System.Data.Linq.Table<BangLuong> BangLuongs
		{
			get
			{
				return this.GetTable<BangLuong>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHĐ> ChiTietHĐs
		{
			get
			{
				return this.GetTable<ChiTietHĐ>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		public System.Data.Linq.Table<HopDong> HopDongs
		{
			get
			{
				return this.GetTable<HopDong>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangCong")]
	public partial class BangCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTinhCong;
		
		private string _CheDoCong;
		
		private string _SoCongNghi;
		
		private string _SoCongTangCa;
		
		private string _MaTinhLuong;
		
		private string _GhiChu;
		
		private EntityRef<BangLuong> _BangLuong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhCongChanging(string value);
    partial void OnMaTinhCongChanged();
    partial void OnCheDoCongChanging(string value);
    partial void OnCheDoCongChanged();
    partial void OnSoCongNghiChanging(string value);
    partial void OnSoCongNghiChanged();
    partial void OnSoCongTangCaChanging(string value);
    partial void OnSoCongTangCaChanged();
    partial void OnMaTinhLuongChanging(string value);
    partial void OnMaTinhLuongChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public BangCong()
		{
			this._BangLuong = default(EntityRef<BangLuong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhCong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTinhCong
		{
			get
			{
				return this._MaTinhCong;
			}
			set
			{
				if ((this._MaTinhCong != value))
				{
					this.OnMaTinhCongChanging(value);
					this.SendPropertyChanging();
					this._MaTinhCong = value;
					this.SendPropertyChanged("MaTinhCong");
					this.OnMaTinhCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheDoCong", DbType="NVarChar(50)")]
		public string CheDoCong
		{
			get
			{
				return this._CheDoCong;
			}
			set
			{
				if ((this._CheDoCong != value))
				{
					this.OnCheDoCongChanging(value);
					this.SendPropertyChanging();
					this._CheDoCong = value;
					this.SendPropertyChanged("CheDoCong");
					this.OnCheDoCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCongNghi", DbType="NVarChar(50)")]
		public string SoCongNghi
		{
			get
			{
				return this._SoCongNghi;
			}
			set
			{
				if ((this._SoCongNghi != value))
				{
					this.OnSoCongNghiChanging(value);
					this.SendPropertyChanging();
					this._SoCongNghi = value;
					this.SendPropertyChanged("SoCongNghi");
					this.OnSoCongNghiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCongTangCa", DbType="NVarChar(50)")]
		public string SoCongTangCa
		{
			get
			{
				return this._SoCongTangCa;
			}
			set
			{
				if ((this._SoCongTangCa != value))
				{
					this.OnSoCongTangCaChanging(value);
					this.SendPropertyChanging();
					this._SoCongTangCa = value;
					this.SendPropertyChanged("SoCongTangCa");
					this.OnSoCongTangCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhLuong", DbType="NChar(10)")]
		public string MaTinhLuong
		{
			get
			{
				return this._MaTinhLuong;
			}
			set
			{
				if ((this._MaTinhLuong != value))
				{
					if (this._BangLuong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTinhLuongChanging(value);
					this.SendPropertyChanging();
					this._MaTinhLuong = value;
					this.SendPropertyChanged("MaTinhLuong");
					this.OnMaTinhLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangLuong_BangCong", Storage="_BangLuong", ThisKey="MaTinhLuong", OtherKey="MaTinhLuong", IsForeignKey=true)]
		public BangLuong BangLuong
		{
			get
			{
				return this._BangLuong.Entity;
			}
			set
			{
				BangLuong previousValue = this._BangLuong.Entity;
				if (((previousValue != value) 
							|| (this._BangLuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangLuong.Entity = null;
						previousValue.BangCongs.Remove(this);
					}
					this._BangLuong.Entity = value;
					if ((value != null))
					{
						value.BangCongs.Add(this);
						this._MaTinhLuong = value.MaTinhLuong;
					}
					else
					{
						this._MaTinhLuong = default(string);
					}
					this.SendPropertyChanged("BangLuong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongBan")]
	public partial class PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPB;
		
		private string _MaNV;
		
		private string _TenPB;
		
		private string _LoaiPB;
		
		private System.Nullable<int> _SĐT;
		
		private string _EmailPB;
		
		private string _ChiNhanhPB;
		
		private string _DiaChiPB;
		
		private string _GhiChu;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPBChanging(string value);
    partial void OnMaPBChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenPBChanging(string value);
    partial void OnTenPBChanged();
    partial void OnLoaiPBChanging(string value);
    partial void OnLoaiPBChanged();
    partial void OnSĐTChanging(System.Nullable<int> value);
    partial void OnSĐTChanged();
    partial void OnEmailPBChanging(string value);
    partial void OnEmailPBChanged();
    partial void OnChiNhanhPBChanging(string value);
    partial void OnChiNhanhPBChanged();
    partial void OnDiaChiPBChanging(string value);
    partial void OnDiaChiPBChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public PhongBan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this.OnMaPBChanging(value);
					this.SendPropertyChanging();
					this._MaPB = value;
					this.SendPropertyChanged("MaPB");
					this.OnMaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPB", DbType="NVarChar(50)")]
		public string TenPB
		{
			get
			{
				return this._TenPB;
			}
			set
			{
				if ((this._TenPB != value))
				{
					this.OnTenPBChanging(value);
					this.SendPropertyChanging();
					this._TenPB = value;
					this.SendPropertyChanged("TenPB");
					this.OnTenPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPB", DbType="NVarChar(50)")]
		public string LoaiPB
		{
			get
			{
				return this._LoaiPB;
			}
			set
			{
				if ((this._LoaiPB != value))
				{
					this.OnLoaiPBChanging(value);
					this.SendPropertyChanging();
					this._LoaiPB = value;
					this.SendPropertyChanged("LoaiPB");
					this.OnLoaiPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SĐT", DbType="Int")]
		public System.Nullable<int> SĐT
		{
			get
			{
				return this._SĐT;
			}
			set
			{
				if ((this._SĐT != value))
				{
					this.OnSĐTChanging(value);
					this.SendPropertyChanging();
					this._SĐT = value;
					this.SendPropertyChanged("SĐT");
					this.OnSĐTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailPB", DbType="NVarChar(50)")]
		public string EmailPB
		{
			get
			{
				return this._EmailPB;
			}
			set
			{
				if ((this._EmailPB != value))
				{
					this.OnEmailPBChanging(value);
					this.SendPropertyChanging();
					this._EmailPB = value;
					this.SendPropertyChanged("EmailPB");
					this.OnEmailPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiNhanhPB", DbType="NVarChar(50)")]
		public string ChiNhanhPB
		{
			get
			{
				return this._ChiNhanhPB;
			}
			set
			{
				if ((this._ChiNhanhPB != value))
				{
					this.OnChiNhanhPBChanging(value);
					this.SendPropertyChanging();
					this._ChiNhanhPB = value;
					this.SendPropertyChanged("ChiNhanhPB");
					this.OnChiNhanhPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiPB", DbType="NVarChar(50)")]
		public string DiaChiPB
		{
			get
			{
				return this._DiaChiPB;
			}
			set
			{
				if ((this._DiaChiPB != value))
				{
					this.OnDiaChiPBChanging(value);
					this.SendPropertyChanging();
					this._DiaChiPB = value;
					this.SendPropertyChanged("DiaChiPB");
					this.OnDiaChiPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhongBan", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhongBans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhongBans.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangLuong")]
	public partial class BangLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTinhLuong;
		
		private string _HeSoLuong;
		
		private string _LuongCoBan_Ngay;
		
		private string _Thuong;
		
		private string _TamUng;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _IsDelete;
		
		private EntitySet<BangCong> _BangCongs;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhLuongChanging(string value);
    partial void OnMaTinhLuongChanged();
    partial void OnHeSoLuongChanging(string value);
    partial void OnHeSoLuongChanged();
    partial void OnLuongCoBan_NgayChanging(string value);
    partial void OnLuongCoBan_NgayChanged();
    partial void OnThuongChanging(string value);
    partial void OnThuongChanged();
    partial void OnTamUngChanging(string value);
    partial void OnTamUngChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnIsDeleteChanging(System.Nullable<bool> value);
    partial void OnIsDeleteChanged();
    #endregion
		
		public BangLuong()
		{
			this._BangCongs = new EntitySet<BangCong>(new Action<BangCong>(this.attach_BangCongs), new Action<BangCong>(this.detach_BangCongs));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhLuong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTinhLuong
		{
			get
			{
				return this._MaTinhLuong;
			}
			set
			{
				if ((this._MaTinhLuong != value))
				{
					this.OnMaTinhLuongChanging(value);
					this.SendPropertyChanging();
					this._MaTinhLuong = value;
					this.SendPropertyChanged("MaTinhLuong");
					this.OnMaTinhLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoLuong", DbType="NVarChar(50)")]
		public string HeSoLuong
		{
			get
			{
				return this._HeSoLuong;
			}
			set
			{
				if ((this._HeSoLuong != value))
				{
					this.OnHeSoLuongChanging(value);
					this.SendPropertyChanging();
					this._HeSoLuong = value;
					this.SendPropertyChanged("HeSoLuong");
					this.OnHeSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[LuongCoBan/Ngay]", Storage="_LuongCoBan_Ngay", DbType="NVarChar(50)")]
		public string LuongCoBan_Ngay
		{
			get
			{
				return this._LuongCoBan_Ngay;
			}
			set
			{
				if ((this._LuongCoBan_Ngay != value))
				{
					this.OnLuongCoBan_NgayChanging(value);
					this.SendPropertyChanging();
					this._LuongCoBan_Ngay = value;
					this.SendPropertyChanged("LuongCoBan_Ngay");
					this.OnLuongCoBan_NgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thuong", DbType="NVarChar(50)")]
		public string Thuong
		{
			get
			{
				return this._Thuong;
			}
			set
			{
				if ((this._Thuong != value))
				{
					this.OnThuongChanging(value);
					this.SendPropertyChanging();
					this._Thuong = value;
					this.SendPropertyChanged("Thuong");
					this.OnThuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamUng", DbType="NVarChar(50)")]
		public string TamUng
		{
			get
			{
				return this._TamUng;
			}
			set
			{
				if ((this._TamUng != value))
				{
					this.OnTamUngChanging(value);
					this.SendPropertyChanging();
					this._TamUng = value;
					this.SendPropertyChanged("TamUng");
					this.OnTamUngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit")]
		public System.Nullable<bool> IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this.OnIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsDelete = value;
					this.SendPropertyChanged("IsDelete");
					this.OnIsDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangLuong_BangCong", Storage="_BangCongs", ThisKey="MaTinhLuong", OtherKey="MaTinhLuong")]
		public EntitySet<BangCong> BangCongs
		{
			get
			{
				return this._BangCongs;
			}
			set
			{
				this._BangCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangLuong_NhanVien", Storage="_NhanViens", ThisKey="MaTinhLuong", OtherKey="MaTinhLuong")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangCongs(BangCong entity)
		{
			this.SendPropertyChanging();
			entity.BangLuong = this;
		}
		
		private void detach_BangCongs(BangCong entity)
		{
			this.SendPropertyChanging();
			entity.BangLuong = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.BangLuong = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.BangLuong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHĐ")]
	public partial class ChiTietHĐ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _MaHĐ;
		
		private System.Nullable<System.DateTime> _NgayKyHĐ;
		
		private System.Nullable<System.DateTime> _NgayKetThucHĐ;
		
		private string _GhiChu;
		
		private EntityRef<HopDong> _HopDong;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaHĐChanging(string value);
    partial void OnMaHĐChanged();
    partial void OnNgayKyHĐChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKyHĐChanged();
    partial void OnNgayKetThucHĐChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetThucHĐChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public ChiTietHĐ()
		{
			this._HopDong = default(EntityRef<HopDong>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHĐ", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHĐ
		{
			get
			{
				return this._MaHĐ;
			}
			set
			{
				if ((this._MaHĐ != value))
				{
					if (this._HopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHĐChanging(value);
					this.SendPropertyChanging();
					this._MaHĐ = value;
					this.SendPropertyChanged("MaHĐ");
					this.OnMaHĐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKyHĐ", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKyHĐ
		{
			get
			{
				return this._NgayKyHĐ;
			}
			set
			{
				if ((this._NgayKyHĐ != value))
				{
					this.OnNgayKyHĐChanging(value);
					this.SendPropertyChanging();
					this._NgayKyHĐ = value;
					this.SendPropertyChanged("NgayKyHĐ");
					this.OnNgayKyHĐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThucHĐ", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKetThucHĐ
		{
			get
			{
				return this._NgayKetThucHĐ;
			}
			set
			{
				if ((this._NgayKetThucHĐ != value))
				{
					this.OnNgayKetThucHĐChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThucHĐ = value;
					this.SendPropertyChanged("NgayKetThucHĐ");
					this.OnNgayKetThucHĐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_ChiTietHĐ", Storage="_HopDong", ThisKey="MaHĐ", OtherKey="MaHĐ", IsForeignKey=true)]
		public HopDong HopDong
		{
			get
			{
				return this._HopDong.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong.Entity = null;
						previousValue.ChiTietHĐs.Remove(this);
					}
					this._HopDong.Entity = value;
					if ((value != null))
					{
						value.ChiTietHĐs.Add(this);
						this._MaHĐ = value.MaHĐ;
					}
					else
					{
						this._MaHĐ = default(string);
					}
					this.SendPropertyChanged("HopDong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChiTietHĐ", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ChiTietHĐs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ChiTietHĐs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCV;
		
		private string _MaNV;
		
		private string _TenCV;
		
		private string _PhuCapCV;
		
		private string _QuyenHan;
		
		private string _NhiemVu;
		
		private string _GhiChu;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenCVChanging(string value);
    partial void OnTenCVChanged();
    partial void OnPhuCapCVChanging(string value);
    partial void OnPhuCapCVChanged();
    partial void OnQuyenHanChanging(string value);
    partial void OnQuyenHanChanged();
    partial void OnNhiemVuChanging(string value);
    partial void OnNhiemVuChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public ChucVu()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(50)")]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this.OnTenCVChanging(value);
					this.SendPropertyChanging();
					this._TenCV = value;
					this.SendPropertyChanged("TenCV");
					this.OnTenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuCapCV", DbType="NVarChar(50)")]
		public string PhuCapCV
		{
			get
			{
				return this._PhuCapCV;
			}
			set
			{
				if ((this._PhuCapCV != value))
				{
					this.OnPhuCapCVChanging(value);
					this.SendPropertyChanging();
					this._PhuCapCV = value;
					this.SendPropertyChanged("PhuCapCV");
					this.OnPhuCapCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenHan", DbType="NVarChar(50)")]
		public string QuyenHan
		{
			get
			{
				return this._QuyenHan;
			}
			set
			{
				if ((this._QuyenHan != value))
				{
					this.OnQuyenHanChanging(value);
					this.SendPropertyChanging();
					this._QuyenHan = value;
					this.SendPropertyChanged("QuyenHan");
					this.OnQuyenHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhiemVu", DbType="NVarChar(50)")]
		public string NhiemVu
		{
			get
			{
				return this._NhiemVu;
			}
			set
			{
				if ((this._NhiemVu != value))
				{
					this.OnNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._NhiemVu = value;
					this.SendPropertyChanged("NhiemVu");
					this.OnNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChucVu", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ChucVus.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ChucVus.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private string _Ghi_chu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnGhi_chuChanging(string value);
    partial void OnGhi_chuChanged();
    #endregion
		
		public DangNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(10)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ghi chu]", Storage="_Ghi_chu", DbType="NChar(10)")]
		public string Ghi_chu
		{
			get
			{
				return this._Ghi_chu;
			}
			set
			{
				if ((this._Ghi_chu != value))
				{
					this.OnGhi_chuChanging(value);
					this.SendPropertyChanging();
					this._Ghi_chu = value;
					this.SendPropertyChanged("Ghi_chu");
					this.OnGhi_chuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDong")]
	public partial class HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHĐ;
		
		private string _TenHĐ;
		
		private string _LoaiHĐ;
		
		private string _ThoiHan;
		
		private string _GhiChu;
		
		private EntitySet<ChiTietHĐ> _ChiTietHĐs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHĐChanging(string value);
    partial void OnMaHĐChanged();
    partial void OnTenHĐChanging(string value);
    partial void OnTenHĐChanged();
    partial void OnLoaiHĐChanging(string value);
    partial void OnLoaiHĐChanged();
    partial void OnThoiHanChanging(string value);
    partial void OnThoiHanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public HopDong()
		{
			this._ChiTietHĐs = new EntitySet<ChiTietHĐ>(new Action<ChiTietHĐ>(this.attach_ChiTietHĐs), new Action<ChiTietHĐ>(this.detach_ChiTietHĐs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHĐ", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHĐ
		{
			get
			{
				return this._MaHĐ;
			}
			set
			{
				if ((this._MaHĐ != value))
				{
					this.OnMaHĐChanging(value);
					this.SendPropertyChanging();
					this._MaHĐ = value;
					this.SendPropertyChanged("MaHĐ");
					this.OnMaHĐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHĐ", DbType="NVarChar(50)")]
		public string TenHĐ
		{
			get
			{
				return this._TenHĐ;
			}
			set
			{
				if ((this._TenHĐ != value))
				{
					this.OnTenHĐChanging(value);
					this.SendPropertyChanging();
					this._TenHĐ = value;
					this.SendPropertyChanged("TenHĐ");
					this.OnTenHĐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHĐ", DbType="NVarChar(50)")]
		public string LoaiHĐ
		{
			get
			{
				return this._LoaiHĐ;
			}
			set
			{
				if ((this._LoaiHĐ != value))
				{
					this.OnLoaiHĐChanging(value);
					this.SendPropertyChanging();
					this._LoaiHĐ = value;
					this.SendPropertyChanged("LoaiHĐ");
					this.OnLoaiHĐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiHan", DbType="NVarChar(50)")]
		public string ThoiHan
		{
			get
			{
				return this._ThoiHan;
			}
			set
			{
				if ((this._ThoiHan != value))
				{
					this.OnThoiHanChanging(value);
					this.SendPropertyChanging();
					this._ThoiHan = value;
					this.SendPropertyChanged("ThoiHan");
					this.OnThoiHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_ChiTietHĐ", Storage="_ChiTietHĐs", ThisKey="MaHĐ", OtherKey="MaHĐ")]
		public EntitySet<ChiTietHĐ> ChiTietHĐs
		{
			get
			{
				return this._ChiTietHĐs;
			}
			set
			{
				this._ChiTietHĐs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHĐs(ChiTietHĐ entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = this;
		}
		
		private void detach_ChiTietHĐs(ChiTietHĐ entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _HoNV;
		
		private string _TenNV;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private string _SĐT;
		
		private string _MaTinhLuong;
		
		private string _GhiChu;
		
		private EntitySet<PhongBan> _PhongBans;
		
		private EntitySet<ChiTietHĐ> _ChiTietHĐs;
		
		private EntitySet<ChucVu> _ChucVus;
		
		private EntityRef<BangLuong> _BangLuong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHoNVChanging(string value);
    partial void OnHoNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSĐTChanging(string value);
    partial void OnSĐTChanged();
    partial void OnMaTinhLuongChanging(string value);
    partial void OnMaTinhLuongChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NhanVien()
		{
			this._PhongBans = new EntitySet<PhongBan>(new Action<PhongBan>(this.attach_PhongBans), new Action<PhongBan>(this.detach_PhongBans));
			this._ChiTietHĐs = new EntitySet<ChiTietHĐ>(new Action<ChiTietHĐ>(this.attach_ChiTietHĐs), new Action<ChiTietHĐ>(this.detach_ChiTietHĐs));
			this._ChucVus = new EntitySet<ChucVu>(new Action<ChucVu>(this.attach_ChucVus), new Action<ChucVu>(this.detach_ChucVus));
			this._BangLuong = default(EntityRef<BangLuong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoNV", DbType="NVarChar(50)")]
		public string HoNV
		{
			get
			{
				return this._HoNV;
			}
			set
			{
				if ((this._HoNV != value))
				{
					this.OnHoNVChanging(value);
					this.SendPropertyChanging();
					this._HoNV = value;
					this.SendPropertyChanged("HoNV");
					this.OnHoNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SĐT", DbType="NChar(10)")]
		public string SĐT
		{
			get
			{
				return this._SĐT;
			}
			set
			{
				if ((this._SĐT != value))
				{
					this.OnSĐTChanging(value);
					this.SendPropertyChanging();
					this._SĐT = value;
					this.SendPropertyChanged("SĐT");
					this.OnSĐTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhLuong", DbType="NChar(10)")]
		public string MaTinhLuong
		{
			get
			{
				return this._MaTinhLuong;
			}
			set
			{
				if ((this._MaTinhLuong != value))
				{
					if (this._BangLuong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTinhLuongChanging(value);
					this.SendPropertyChanging();
					this._MaTinhLuong = value;
					this.SendPropertyChanged("MaTinhLuong");
					this.OnMaTinhLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhongBan", Storage="_PhongBans", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<PhongBan> PhongBans
		{
			get
			{
				return this._PhongBans;
			}
			set
			{
				this._PhongBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChiTietHĐ", Storage="_ChiTietHĐs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<ChiTietHĐ> ChiTietHĐs
		{
			get
			{
				return this._ChiTietHĐs;
			}
			set
			{
				this._ChiTietHĐs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChucVu", Storage="_ChucVus", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<ChucVu> ChucVus
		{
			get
			{
				return this._ChucVus;
			}
			set
			{
				this._ChucVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangLuong_NhanVien", Storage="_BangLuong", ThisKey="MaTinhLuong", OtherKey="MaTinhLuong", IsForeignKey=true)]
		public BangLuong BangLuong
		{
			get
			{
				return this._BangLuong.Entity;
			}
			set
			{
				BangLuong previousValue = this._BangLuong.Entity;
				if (((previousValue != value) 
							|| (this._BangLuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangLuong.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._BangLuong.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._MaTinhLuong = value.MaTinhLuong;
					}
					else
					{
						this._MaTinhLuong = default(string);
					}
					this.SendPropertyChanged("BangLuong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhongBans(PhongBan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhongBans(PhongBan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_ChiTietHĐs(ChiTietHĐ entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ChiTietHĐs(ChiTietHĐ entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_ChucVus(ChucVu entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ChucVus(ChucVu entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
}
#pragma warning restore 1591
